{% set name = "napari-deeplabcut" %}
{% set version = "0.3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari_deeplabcut-{{ version }}.tar.gz
  sha256: b04323d8d98650f5370fd79f9f759914763ac70f318ddc0e6286314bb5fb7a8c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm
  run:
    - dask-core              #  Imported but not listed as requirement
    - dask-image
    - matplotlib-base >=3.3
    - napari <0.5.0
    - natsort
    - numpy
    - opencv
    - pandas
    - pytables               # Listed as requirement but not imported
    - python >=3.9
    - pyyaml
    - qtpy >=2.4
    - scikit-image
    - scipy

test:
  imports:
    - napari_deeplabcut
  commands:
    - pip list
    # - pip check  # Can be uncommented when upstream requirements are updated/corrected
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-deeplabcut
  summary: napari + DeepLabCut annotation tool
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/DeepLabCut/napari-deeplabcut

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jeylau
